ALTER TABLE FORESPOERSEL
ADD FORESPOERSEL_TYPE VARCHAR(50);

UPDATE FORESPOERSEL SET FORESPOERSEL_TYPE = 'BESTILT_AV_FAGSYSTEM' where FORESPOERSEL_TYPE is null;

ALTER TABLE FORESPOERSEL ALTER COLUMN FORESPOERSEL_TYPE SET NOT NULL;

ALTER TABLE FORESPOERSEL ALTER COLUMN SKJAERINGSTIDSPUNKT DROP NOT NULL;
ALTER TABLE FORESPOERSEL ALTER COLUMN FAGSYSTEM_SAKSNUMMER DROP NOT NULL;
